version: "3.9"


services:
  bot:
    container_name: doremi
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    networks:
      - doremi_network
    depends_on:
      - server
  server:
    container_name: doremi_server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    networks:
      - doremi_network
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    container_name: doremi_database
    image: mariadb:10.9.4
    volumes:
      - "./data/:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
      - "./sql/:/docker-entrypoint-initdb.d/"
    env_file:
      - ./.mariadb.env
    ports:
      - "1501:3306"
    networks:
      - doremi_network

networks:
  doremi_network: {}
